// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPQlXdNzFo2_FrV8suCu7sLoVP4vc5fok',
    appId: '1:143878781286:web:135a7fdc10b79a9a4430a7',
    messagingSenderId: '143878781286',
    projectId: 'apk-magang',
    authDomain: 'apk-magang.firebaseapp.com',
    storageBucket: 'apk-magang.firebasestorage.app',
    measurementId: 'G-FM62JCXZJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHciRl7k6A3UsyRbnk5AQYOThBKzutpHo',
    appId: '1:143878781286:android:51b5edb941cab8bd4430a7',
    messagingSenderId: '143878781286',
    projectId: 'apk-magang',
    storageBucket: 'apk-magang.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBubuPPihXHpPKFUSYp82qU2WtSxQA-CCY',
    appId: '1:143878781286:ios:e492cabab5ca0a734430a7',
    messagingSenderId: '143878781286',
    projectId: 'apk-magang',
    storageBucket: 'apk-magang.firebasestorage.app',
    iosBundleId: 'com.example.apkAbsenMagang',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBubuPPihXHpPKFUSYp82qU2WtSxQA-CCY',
    appId: '1:143878781286:ios:e492cabab5ca0a734430a7',
    messagingSenderId: '143878781286',
    projectId: 'apk-magang',
    storageBucket: 'apk-magang.firebasestorage.app',
    iosBundleId: 'com.example.apkAbsenMagang',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPQlXdNzFo2_FrV8suCu7sLoVP4vc5fok',
    appId: '1:143878781286:web:468392af13ab98884430a7',
    messagingSenderId: '143878781286',
    projectId: 'apk-magang',
    authDomain: 'apk-magang.firebaseapp.com',
    storageBucket: 'apk-magang.firebasestorage.app',
    measurementId: 'G-8KB5Y5WF25',
  );
}
